"""
Django settings for mdac project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f45+k$ux&n#$wb@!=m((*8ky8e%&732$iu-s4&s0=ht*bt=)ud'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['mdac-73749563213.europe-west3.run.app', 'rozluchennia-alimenty.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'solo',
    'main',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mdac.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mdac.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "MDAC Admin",
    "site_header": "MDAC Адмінка",
    "site_brand": "MDAC",
    "welcome_sign": "Вітаємо в адмінці MDAC!",
    "copyright": "MDAC",
    "search_model": ["main.Service", "main.ContactRequest"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "main.Service": "fas fa-briefcase",
        "main.ContactRequest": "fas fa-envelope",
        "main.SiteConfiguration": "fas fa-cogs",
        "main.HeroBanner": "fas fa-image",
        "main.MenuItem": "fas fa-bars",
        "main.SectionBackground": "fas fa-paint-brush",
        "main.Advantage": "fas fa-star",
        "main.Testimonial": "fas fa-comment",
        "main.AlgorithmStep": "fas fa-list-ol",
        "main.FAQ": "fas fa-question-circle",
        "main.Bonus": "fas fa-gift",
        "main.ServiceCategoryDescription": "fas fa-tags",
        "main.Result": "fas fa-check-circle",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-dot-circle",
    "order_with_respect_to": [
        "main.SiteConfiguration",
        "main.HeroBanner",
        "main.MenuItem",
        "main.Service",
        "main.ServiceCategoryDescription",
        "main.Advantage",
        "main.Result",
        "main.Testimonial",
        "main.AlgorithmStep",
        "main.FAQ",
        "main.Bonus",
        "main.SectionBackground",
        "main.ContactRequest",
    ],
    # "site_logo": "logos/your_logo.png",  # Розкоментуйте і вкажіть шлях до вашого лого, якщо потрібно
    # "site_icon": "logos/your_logo.png",  # favicon
    # "custom_css": "css/my_admin.css",   # Додайте власний CSS, якщо потрібно
}

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
        'language': 'uk',
    },
}
