# Generated by Django 5.2.3 on 2025-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва переваги')),
                ('description', models.TextField(verbose_name='Опис переваги')),
                ('icon_class', models.CharField(max_length=50, verbose_name='Клас іконки Font Awesome (напр. fa-bolt)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AlgorithmStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва кроку')),
                ('description', models.TextField(verbose_name='Опис кроку')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Номер кроку (порядок)')),
            ],
            options={
                'verbose_name': 'Крок алгоритму',
                'verbose_name_plural': 'Кроки алгоритму',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст акції / бонусу')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Акція / Бонус',
                'verbose_name_plural': 'Акції та Бонуси',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField(verbose_name='Опис ситуації')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Оброблено')),
            ],
            options={
                'verbose_name': 'Заявка з сайту',
                'verbose_name_plural': 'Заявки з сайту',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Часте запитання',
                'verbose_name_plural': 'Часті запитання',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Головний заголовок')),
                ('background_image', models.ImageField(upload_to='banners/', verbose_name='Фонове зображення банера')),
                ('button1_text', models.CharField(max_length=50, verbose_name='Текст кнопки 1')),
                ('button1_link', models.CharField(default='#', max_length=200, verbose_name='Посилання для кнопки 1')),
                ('button2_text', models.CharField(max_length=50, verbose_name='Текст кнопки 2')),
                ('button2_link', models.CharField(default='#', max_length=200, verbose_name='Посилання для кнопки 2')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону під кнопками')),
            ],
            options={
                'verbose_name': 'Головний банер',
                'verbose_name_plural': 'Головний банер',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='Текст пункту меню')),
                ('link', models.CharField(max_length=200, verbose_name='Посилання (напр. #results)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункти меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок під зображенням')),
                ('case_image', models.ImageField(upload_to='results/', verbose_name='Зображення судового рішення (скріншот)')),
                ('case_url', models.URLField(max_length=500, verbose_name='Пряме посилання на рішення в реєстрі')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Рішення (Результат)',
                'verbose_name_plural': 'Рішення (Результати)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ALIMONY', 'Фон для секції аліментів'), ('BONUSES', 'Фон для секції бонусів'), ('TESTIMONIALS', 'Фон для секції відгуків'), ('CONTACT', 'Фон для контактної форми')], max_length=50, unique=True, verbose_name='Секція')),
                ('background_image', models.ImageField(upload_to='backgrounds/', verbose_name='Фонове зображення')),
            ],
            options={
                'verbose_name': 'Фонове зображення секції',
                'verbose_name_plural': 'Фонові зображення секцій',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мітка, напр. «Під ключ»')),
                ('category', models.CharField(choices=[('DIVORCE', 'Розірвання шлюбу'), ('ALIMONY', 'Стягнення аліментів')], max_length=10, verbose_name='Категорія')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DIVORCE', 'Розірвання шлюбу'), ('ALIMONY', 'Стягнення аліментів')], max_length=10, unique=True, verbose_name='Категорія')),
                ('description', models.TextField(verbose_name='Описовий текст для секції')),
            ],
            options={
                'verbose_name': 'Опис категорії послуг',
                'verbose_name_plural': 'Описи категорій послуг',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo_text', models.CharField(default='ЛОГОТИП', max_length=50, verbose_name='Текст логотипу в хедері')),
                ('footer_logo_text', models.CharField(default='ЛОГОТИП', max_length=50, verbose_name='Текст логотипу в футері')),
                ('footer_tagline', models.TextField(verbose_name='Текст-слоган у футері')),
                ('footer_contacts_title', models.CharField(default='КОНТАКТИ', max_length=50, verbose_name="Заголовок 'Контакти' у футері")),
                ('footer_phone', models.CharField(max_length=20, verbose_name='Номер телефону у футері')),
                ('footer_email', models.EmailField(max_length=254, verbose_name='Email у футері')),
                ('footer_cta_text', models.CharField(default='Безкоштовна консультація', max_length=100, verbose_name='Текст кнопки у футері')),
                ('footer_cta_link', models.CharField(default='#', max_length=200, verbose_name='Посилання для кнопки у футері')),
                ('divorce_section_title', models.CharField(default='РОЗІРВАННЯ ШЛЮБУ', max_length=100, verbose_name="Заголовок секції 'Розірвання шлюбу'")),
                ('alimony_section_title', models.CharField(default='СТЯГНЕННЯ АЛІМЕНТІВ', max_length=100, verbose_name="Заголовок секції 'Стягнення аліментів'")),
                ('packages_subtitle', models.CharField(default='Пакети послуг', max_length=100, verbose_name="Підзаголовок 'Пакети послуг'")),
                ('advantages_section_title', models.CharField(default='НАШІ ПЕРЕВАГИ', max_length=100, verbose_name="Заголовок секції 'Переваги'")),
                ('results_section_title', models.CharField(default='НАШІ РІШЕННЯ', max_length=100, verbose_name="Заголовок секції 'Рішення'")),
                ('results_section_subtitle', models.CharField(default='ЗА 2022-2025 РІК', max_length=100, verbose_name="Підзаголовок секції 'Рішення'")),
                ('results_button_text', models.CharField(default='Переглянути всі', max_length=50, verbose_name="Текст кнопки 'Переглянути всі'")),
                ('testimonials_section_title', models.CharField(default='ВІДГУКИ КЛІЄНТІВ', max_length=100, verbose_name="Заголовок секції 'Відгуки'")),
                ('algorithm_section_title', models.CharField(default='АЛГОРИТМ СПІВПРАЦІ З НАМИ', max_length=100, verbose_name="Заголовок секції 'Алгоритм'")),
                ('faq_section_title', models.CharField(default='ЧАСТІ ЗАПИТАННЯ', max_length=100, verbose_name="Заголовок секції 'Часті запитання'")),
                ('bonuses_section_title', models.CharField(default='АКЦІЇ ТА БОНУСИ', max_length=100, verbose_name="Заголовок секції 'Бонуси'")),
                ('contact_form_title', models.CharField(default='Задати інше запитання', max_length=100, verbose_name='Заголовок контактної форми')),
                ('contact_form_subtitle', models.TextField(verbose_name='Підзаголовок контактної форми')),
            ],
            options={
                'verbose_name': 'Налаштування Сайту',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('author', models.CharField(max_length=100, verbose_name="Автор (напр. 'Олександр, м. Львів')")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['order'],
            },
        ),
    ]
