# Generated by Django 5.2.3 on 2025-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ['order'], 'verbose_name': '4. Перевага', 'verbose_name_plural': '4. Переваги'},
        ),
        migrations.AlterModelOptions(
            name='algorithmstep',
            options={'ordering': ['order'], 'verbose_name': '7. Крок алгоритму', 'verbose_name_plural': '7. Кроки алгоритму'},
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['order'], 'verbose_name': '9. Акція / Бонус', 'verbose_name_plural': '9. Акції та Бонуси'},
        ),
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '10. Заявка з сайту', 'verbose_name_plural': '10. Заявки з сайту'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': '8. Часте запитання', 'verbose_name_plural': '8. Часті запитання'},
        ),
        migrations.AlterModelOptions(
            name='herobanner',
            options={'verbose_name': 'Головний банер (не використовується)', 'verbose_name_plural': 'Головний банер (не використовується)'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': '1. Пункт меню', 'verbose_name_plural': '1. Пункти меню'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['order'], 'verbose_name': '5. Рішення (Результат)', 'verbose_name_plural': '5. Рішення (Результати)'},
        ),
        migrations.AlterModelOptions(
            name='sectionbackground',
            options={'verbose_name': '2. Фонове зображення секції', 'verbose_name_plural': '2. Фонові зображення секцій'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': '3. Послуга', 'verbose_name_plural': '3. Послуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategoryinfo',
            options={'verbose_name': '3.1. Опис категорії послуг', 'verbose_name_plural': '3.1. Описи категорій послуг'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': '0. Налаштування Сайту', 'verbose_name_plural': '0. Налаштування Сайту'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order'], 'verbose_name': '6. Відгук', 'verbose_name_plural': '6. Відгуки'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_carousel_text_1',
            field=models.CharField(default='під ключ', max_length=50, verbose_name='Текст каруселі 1'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_carousel_text_2',
            field=models.CharField(default='онлайн', max_length=50, verbose_name='Текст каруселі 2'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_carousel_text_3',
            field=models.CharField(default='24/7', max_length=50, verbose_name='Текст каруселі 3'),
        ),
    ]
