# Generated by Django 5.2.3 on 2025-06-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_advantage_options_alter_algorithmstep_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'verbose_name': '1. Головний банер', 'verbose_name_plural': '1. Головний банер'},
        ),
    ]
