# Generated by Django 5.2.3 on 2025-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_herobanner_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobanner',
            name='background_image',
        ),
        migrations.AlterField(
            model_name='sectionbackground',
            name='name',
            field=models.CharField(choices=[('ALIMONY', 'Фон для секції аліментів'), ('BONUSES', 'Фон для секції бонусів'), ('TESTIMONIALS', 'Фон для секції відгуків'), ('CONTACT', 'Фон для контактної форми'), ('HOME_BANER', 'Фон для головного банера')], max_length=50, unique=True, verbose_name='Секція'),
        ),
    ]
